[package]
name = "lsm6dsv32"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
embassy-stm32 = { version = "0.4.0", features = [ "defmt", "exti"]  }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime" ] }

defmt = "1.0.1"
defmt-rtt = "1.0.0"

embedded-hal = "0.2.6"

[profile.release]
debug = 2
